### ISSUE TITLE
KB files need update

### ISSUE THREAD

**Issue by anupamahp22** [blackducksoftware/import_yocto_bm#18]
Hello,

KB files need to be updated. They are missing curl 8.1.2 at least.
Please do the needful.

Thanks in advance
Anupama

**Comment by luca-fancellu** [comment]
How are these KB files generated?

**Comment by est-flouveau** [comment]
Hi, is it possible to update the KB as it is not updated since 10 months.

**Comment by vladhed** [comment]
maybe dumb question, but can we just raise our own PRs to update the KB files?  I've been updating my copied of the files and using --kb_recipe_dir, but it does occur to me my updates might be useful to others.
