### ISSUE TITLE
Typo: manifest files never are dirs

### ISSUE THREAD

**Issue by arnemertz** [blackducksoftware/import_yocto_bm#4]
The following condition will almost always be false:

https://github.com/blackducksoftware/import_yocto_bm/blob/80c8b2d0fdf0c43c3e6f73aa4536ead4b3026d1c/import_yocto_bm/config.py#L472
`isdir` should be `isfile` here.

In my case, even though I had the manifest file passed correctly as argument, this resulted in hours of globbing through the build directory: It is a slightly larger project and some of the OSS projects (e.g. poky/meta/recipes-support/attr/acl) seem to think it is a good idea to have directory symlinks that point to the same directory - resulting in recursions that are only broken by OSErrors

```
OSError: [Errno 40] Too many levels of symbolic links: 'build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/acl/2.2.52-r0/acl-2.2.52/include/acl/acl/acl/acl/acl/acl/acl/acl/acl/acl/acl/acl/acl/acl/acl/sys/sys/sys/acl/sys/acl/sys/acl/acl/acl/sys/sys/acl/acl/sys/sys/sys/sys/acl/acl/acl/acl/sys/sys/sys/acl'
```

So, in addition to fix the obvious error above, maybe the globbing can be improved as well.

**Comment by matthewb66** [comment]
Thanks for this catch.
I am also going to add an extra question in the wizard whether searching recursively is required (allowing it to be skipped).
Version 2.2 will include these changes.
