### ISSUE TITLE
Unable to use the tool on non-secure black duck server

### ISSUE THREAD

**Issue by RaveenReddy** [blackducksoftware/import_yocto_bm#8]
I am trying to run the tool on yocto Zeus.
I try to bypass the certificate as the server I am using is insecure.
And I see below errors
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

Attached file " [BD_CertIssue.txt](https://github.com/blackducksoftware/import_yocto_bm/files/8115879/BD_CertIssue.txt) " have detailed log.

Steps followed
1. Install black duck and import_yocto_bm through pip3
2. Download and build yocto - zeus.
3. Run import_yocto_bm with command   
              **import_yocto_bm --blackduck_url "" --blackduck_api_token "" -p "" -v ""**

**Comment by RaveenReddy** [comment]
The attached error was due to the proxy settings.
However there are some other issues occurred while posting the scan data to the server when SSL verification is disabled.
I guess the problem is utils.py::upload_json() where requests.post() is used, may be it needs to be passed with global verify flag

**Comment by matthewb66** [comment]
Please refer to the documentation and supported options.
Specify the option --blackduck_trust_cert to ignore certificate errors if you are using an insecure server.
